[workspace]
members = [
    "api",
    "common",
    "modules/nlp/question-answering",
    "modules/vision/image-classification",
    "modules/vision/image-classification/example",
    "pallet",
    "runtime",
]
default-members = []
